### ISSUE TITLE
We need a beautiful example at the home page :)

### ISSUE THREAD

**Issue by villares** [hx2A/py5book#1]
Could be the same as in the original docs...
![image](https://user-images.githubusercontent.com/3694604/133001329-759dfd4c-ad5a-4527-a384-22b1b0523eb0.png)
![image](https://user-images.githubusercontent.com/3694604/133001341-5c1619f5-4bf6-4893-8f1f-663fca03131b.png)

**Comment by hx2A** [comment]
Agreed! I will create a few.

**Comment by hx2A** [comment]
The new documentation website is live!

I'm not sure if the example on the home page is "beautiful", but the code can be executed and embedded in the page itself using the Live Code feature, and that has its own kind of beauty.
