### ISSUE TITLE
Strange cell/message in the py5bot intro

### ISSUE THREAD

**Issue by villares** [hx2A/py5book#122]
I couldn't find this cell here in the repo, could it be a remnant/left-over of an older build?
Or an "overreacting" warning caused by the `draw_random_circle()` function in the previous cell?

![image](https://github.com/user-attachments/assets/913e7dc4-9930-4e6d-a9aa-73a9fd494823)

"Your code contains a draw function..."

**Comment by hx2A** [comment]
Yikes! I need to fix that right away. Thanks for spotting this

**Comment by hx2A** [comment]
This is a bug

**Comment by hx2A** [comment]
Thank you for spotting this. This is a bug that has been in py5 for a while. I regret it was not detected until now.

I opened an issue and will fix it in the next release.

**Comment by hx2A** [comment]
I am going to close this now that https://github.com/py5coding/py5generator/issues/490 is closed.
