### ISSUE TITLE
Images missing at "Numpy, Arrays, and Images"

### ISSUE THREAD

**Issue by villares** [hx2A/py5book#125]
Please check https://py5coding.org/integrations/numpy.html

Maybe OpenCV (`cv2`)  was missing from the docs build env?

```---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 3
      1 from itertools import product
----> 3 import cv2
      4 import numpy as np
      5 from PIL import Image

ModuleNotFoundError: No module named 'cv2'
```

**Comment by hx2A** [comment]
Excellent, thank  you for noticing this.

When I rebuilt the website I did not look carefully at the Jupyter Book logs. I was able to find a similar problem on the colour page. I just fixed all of the issues with the logs.

If you see any other issues, please let me know!
