### ISSUE TITLE
MyBinder can't find the `colour` module

### ISSUE THREAD

**Issue by villares** [hx2A/py5book#128]
![image](https://github.com/user-attachments/assets/81226a61-178a-4682-9908-f6682786a990)

I might open another issue about this page, proposing you move the black stripe that demonstrates color opacity/transparency a bit to the side so that reading the hex codes is easier.

**Comment by hx2A** [comment]
Thanks for spotting this, @villares ! I just fixed this for this repo and the py5examples repo.
