### ISSUE TITLE
`run_sketch` description of blocking behavior contradicts code

### ISSUE THREAD

**Issue by camblomquist** [hx2A/py5book#46]
> Blocking is not supported on OSX. This is because of the (current) limitations of py5 on OSX. If the block parameter is set to `True`, a warning message will appear and it will be changed to `False`.

However, attempting to `run_sketch` with `block=False` will print the following error
> On OSX, blocking is manditory when Sketch is not run through Jupyter. This applies to all renderers.

It appears that the doc is referring specifically to blocking behavior when running through Jupyter on OSX, which is correct according to https://github.com/py5coding/py5generator/blob/main/py5_resources/py5_module/py5/sketch.py#L233

**Comment by hx2A** [comment]
@camblomquist , thanks for identifying this point of confusion.

Your first quote is from the [run_sketch()](http://py5coding.org/reference/sketch_run_sketch.html) documentation, which I can see is out of date. What is written there was true for py5 earlier this year but was not updated as I made some improvements to the OSX issues.

What is current is the [Special Notes for OSX Users](http://py5coding.org/content/osx_users.html). That page provides more info and correct info about py5 on OSX.

I'll fix the documentation issue in the near future.

**Comment by hx2A** [comment]
This is now fixed
