### ISSUE TITLE
Tried to build, but got: raise DeadKernelError("Kernel died")

### ISSUE THREAD

**Issue by tabreturn** [hx2A/py5book#5]
I've installed the packages in the requirements file (and py5 and JRE). I run a `jb build .` but I get the following error --

```
Exception occurred:
  File ".../lib/python3.9/site-packages/nbclient/client.py", line 953, in async_execute_cell
    raise DeadKernelError("Kernel died")
nbclient.exceptions.DeadKernelError: Kernel died
```

Any ideas?

**Comment by hx2A** [comment]
Have you installed both of py5's Jupyter notebook kernels? Also, you should
use the makefile. Are you on Linux?

**Comment by hx2A** [comment]
Also, I recommend ignoring the requirements file in the py5book repo. That looks like a file created by default when I started the Jupyter book project. When I use py5book I use the same anaconda environment I use for py5generator. Try using that one, and then add py5 and py5jupyter, and then install the kernels. 

When you get it working, please make a PR to fix this for the next person.

**Comment by tabreturn** [comment]
Thanks for the quick response. It looks like it was a Java issue on my side -- I hadn't added my Java executables to PATH. Doh! I've got my PC (Linux) set up this way for testing the Thonny plug-in.

Just for the record -- I'm using Python3.9 (not Anaconda). I installed py5jupyter, jupyter-book, and the py5jupyter.kernels

Everything builds fine :+1:
