### ISSUE TITLE
The reference index/summary page

### ISSUE THREAD

**Issue by villares** [hx2A/py5book#51]
We had kind of started this conversation somewhere else (in Discussions, probably), and there is no hurry, but I really think we could improve the reference by creating a true landing place to direct learners.

I know there are site infrastructure limitations right now, so I'll be patient, but I'll throw in some ideas, this is a thing that is bothering me:

http://py5coding.org/reference/sketch.html has the big table I came to love and expect from https://processing.org/reference or even tired https://py.processing.org/reference, but it is buried down after some technical details:

![image](https://user-images.githubusercontent.com/3694604/205698255-4fde8d17-9361-47f5-8eb3-c596bde985db.png)
 
This can't be the first thing a student sees in their first py5 class!

We need a streamlined landing page with the table from current `sketch.html`, and links to the other classes (like Py5Image, Py5Font etc..). 

- I feel like we shouldn't have the technical implementation details upfront, first thing. They are distracting, confusing for beginners. How can we have them for advanced users but out of the way for beginners?
- The list of event functions is important, and it could be made of links to pages related to each event with examples, but maybe after the big methods table.

**Comment by hx2A** [comment]
Can you think of a way to make that page's preamble more parsimonious?

I think the first two sentences are important but the rest can probably move somewhere else. The list of event functions could be a table instead of a list, which would take up less vertical space and shrink things down. But it is probably better to move that stuff elsewhere instead.

**Comment by villares** [comment]
Do you mean these sentences?

> Core py5 class for leveraging py5’s functionality. This is analogous to the PApplet class in Processing. Launch the Sketch with the [run_sketch()](http://py5coding.org/reference/sketch_run_sketch.html) method.

Please don't get me wrong, but I think these don't help at all someone in their first contact with the ideas of drawing with code. 

So I think a solution could be: leave this page with the technical detail as it is, or improve it if you must, for the intermediate and advanced users, but, let's have another simplified landing page for the beginners. Just with links to the methods a the classes?

I'll see if I can make a mock up of the page soon.  Maybe it could go here:

![image](https://user-images.githubusercontent.com/3694604/206297582-5835cb3c-23a0-461d-a150-2a7e43f3fe4f.png)

I know you like to keep all automated so that if a new Processing method comes in it will all update, but this could be a handcrafted begginer friendly summary I'd like to try out... I was looking at the categories that come from Processing and I think we could even improve on that!

**Comment by villares** [comment]
Work in Progress: https://hackmd.io/@villares/py5-reference-summary

**Comment by villares** [comment]
I see that there are pages for each of the "event functions" at the Processing Java reference, they are filed under the *Input* category. I couldn't find our py5 equivalent. Would you like me to write them, @hx2A?
Example: https://processing.org/reference/keyReleased_.html

**Comment by villares** [comment]
> Work in Progress: https://hackmd.io/@villares/py5-reference-summary

Hey @hx2A, @marcovicci  and @tabreturn. No hurry to reply, but I'd like you to take a look at this preliminary document/idea (anyone with the link can edit by signing in).

**Comment by villares** [comment]
I had some intuition that learners wouldn't know what "2D Primitives" are...
I don't even like "Simple 2D Shapes" anymore. I tried "Basic Elements" because lines and points can be 3D also.

![image](https://user-images.githubusercontent.com/3694604/206601780-1104b695-2d06-4807-9a28-e09a75f69962.png)

**Comment by hx2A** [comment]
Finally getting caught up with documentation.

Look here:

http://py5dev.ixora.io/reference/summary.html

for this page added to the documentation website.

Thank you for writing it! It is clear this was a lot of work to put together.

**Comment by hx2A** [comment]
Closing this now. Very glad to have this summary. Thank you!!
